
package fr.leo.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueWS", targetNamespace = "http://service.leo.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueWS {


    /**
     * 
     * @return
     *     returns java.util.List<fr.leo.service.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://service.leo.fr/", className = "fr.leo.service.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://service.leo.fr/", className = "fr.leo.service.GetComptesResponse")
    @Action(input = "http://service.leo.fr/BanqueWS/getComptesRequest", output = "http://service.leo.fr/BanqueWS/getComptesResponse")
    public List<Compte> getComptes();

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ConverionEuroToFranc")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ConverionEuroToFranc", targetNamespace = "http://service.leo.fr/", className = "fr.leo.service.ConverionEuroToFranc")
    @ResponseWrapper(localName = "ConverionEuroToFrancResponse", targetNamespace = "http://service.leo.fr/", className = "fr.leo.service.ConverionEuroToFrancResponse")
    @Action(input = "http://service.leo.fr/BanqueWS/ConverionEuroToFrancRequest", output = "http://service.leo.fr/BanqueWS/ConverionEuroToFrancResponse")
    public double converionEuroToFranc(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param code
     * @return
     *     returns fr.leo.service.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://service.leo.fr/", className = "fr.leo.service.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://service.leo.fr/", className = "fr.leo.service.GetCompteResponse")
    @Action(input = "http://service.leo.fr/BanqueWS/getCompteRequest", output = "http://service.leo.fr/BanqueWS/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        Long code);

}
